Allow anonymous data proc for kvstore get
Nim 1.2.12 has trouble compiling kvstore clients that attempt to fetch
data by passing an anonymous proc to `get`, i.e.,
```
    db.get(key, proc(data: openArray[byte]) = v = @data)[]
```
leads to a compilation error such as:
```
    internal error: expr: param not init data_34695004
```

Note that defining the proc in a named fashion, then passing the name,
works fine. Nim 1.4.8 also succeeds in the case of an anonymous proc.

The error seems to show up due to an interaction with templates taking
`openArray` procs. As the kvstore functions do not need to use templates
this patch replaces them with inline procs. Furthermore, an additional
test checks that passing an anonymous proc works as expected.

A minimal standalone program triggering the same compilation problem:

```
    type
      X* = ref object
        bar: proc (p: proc(v: openArray[byte]))

    template foo(x: X, p: proc(v: openArray[byte])) =
      x.bar(p)

    X().foo(proc(v: openArray[byte]) = discard @v)
```

See https://github.com/nim-lang/Nim/issues/18648